### PR TITLE
Rewrite this

### PR DESCRIPTION
**Pull request by satoufuyuki**

### CODE REVIEW

**Comment by satoufuyuki** [comment]
Fix the conflict LOL

**Review by mzrtamp — APPROVED** [review]
Ampun suhu :pray:

**Review by mzrtamp — APPROVED** [review]
Zeeb

**Comment by Mednoob** [comment]
banyak conflict

**Comment by mzrtamp** [comment]
Memang, katanya jangan di merge dulu, gabisa lagian :v

**Comment by Mednoob** [comment]
oalah ok ok

**Comment by Hazmi35** [comment]
merge aja, accept all changes

**Review by mzrtamp — APPROVED** [review]
Gimana sihh :(

**Pull request merged**
